# This file is for GitHub's sponsor button.
# If you like my work and want to say more than thanks, feel free to buy me a coffee or gift!
custom: ['https://paypal.me/sethc95/3', 'https://www.amazon.com/hz/wishlist/ls/S7YILFHYK0IZ']
